#!/usr/bin/env bash

search='#isolate'

filename="$1"

stem="${filename%%.*}"


makeobjs="${stem}objs ="
makesrcs="${stem}srcs ="

linenum=1
sectfilename="${stem}_main.c"


fix_sfname() {
        local oldname="$1"
        if [[ "$oldname" != "${stem}_.c" ]]; then
                return 0
        fi
        local oldonam="${oldname%%.c}.o"
        local shaval=`sha256sum < "$oldname" | cut -d' ' -f1`
        local newname="${stem}_${shaval}.c"
        local newonam="${newname%%.c}.o"
        echo "$makeobjs"
        makeobjs="${makeobjs%%$oldonam}$newonam"
        echo "$makeobjs"
        makesrcs="${makesrcs%%$oldname}$newname"
        mv "$oldname" "$newname"
}


if [[ `head -n 1 "$filename"` != ${search}* ]]; then
        echo "#line $linenum \"$filename\"" > "$sectfilename"
        makeobjs+=" ${sectfilename%%.c}.o"
        makesrcs+=" $sectfilename"
fi

IFS_BACK=${IFS}

while IFS= read -r line; do
        ((linenum++))
        if [[ "$line" == ${search}* ]]; then
                fix_sfname "$sectfilename"
                sectname="${line/#$search/}"
                sectname="${sectname#"${sectname%%[![:space:]]*}"}"
                sectname="${sectname%"${sectname##*[![:space:]]}"}"
                sectfilename="${stem}_${sectname}.c"

                echo "#line ${linenum} \"$filename\"" > "$sectfilename"
                makeobjs+=" ${sectfilename%%.c}.o"
                makesrcs+=" $sectfilename"
        else
                echo "${line}" >> "$sectfilename"
        fi
done < "$filename"

IFS=${IFS_BACK}

makename="${stem}.mk"

echo "ICOBJECTS += ${stem}.o" > "$makename"
echo "ICCLEANS += ${stem}clean" >> "$makename"
echo "$makeobjs" >> "$makename"
echo "$makesrcs" >> "$makename"
echo "${stem}.o: \$(${stem}objs)" >> "$makename"
echo -e "\tld -r -o \$@ \$^" >> "$makename"
echo "\$(${stem}objs): $makename" >> "$makename"
echo -e "\t\$(CC) -c \$(CFLAGS) \$*.c" >> "$makename"
echo "${stem}clean:" >> "$makename"
echo -e "\t-rm -f \$(${stem}objs) \$(${stem}srcs)" >> "$makename"
